// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_1tmnsismiEttsLJEVTBERoOgGHz3BLk',
    appId: '1:1057931723394:web:670c8fe39c6581c8e56a9b',
    messagingSenderId: '1057931723394',
    projectId: 'instagram-clone-0606',
    authDomain: 'instagram-clone-0606.firebaseapp.com',
    storageBucket: 'instagram-clone-0606.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmPLnhSc8m4ISPva0fLx1WF-D6opv_ZM',
    appId: '1:1057931723394:android:9fbdee4eca90b679e56a9b',
    messagingSenderId: '1057931723394',
    projectId: 'instagram-clone-0606',
    storageBucket: 'instagram-clone-0606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_gCmPV_InLJuu4QkXpNNbwcpwFq6K-VI',
    appId: '1:1057931723394:ios:b0f57cd0dae5902ae56a9b',
    messagingSenderId: '1057931723394',
    projectId: 'instagram-clone-0606',
    storageBucket: 'instagram-clone-0606.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_gCmPV_InLJuu4QkXpNNbwcpwFq6K-VI',
    appId: '1:1057931723394:ios:b0f57cd0dae5902ae56a9b',
    messagingSenderId: '1057931723394',
    projectId: 'instagram-clone-0606',
    storageBucket: 'instagram-clone-0606.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_1tmnsismiEttsLJEVTBERoOgGHz3BLk',
    appId: '1:1057931723394:web:0a435e4045d12edbe56a9b',
    messagingSenderId: '1057931723394',
    projectId: 'instagram-clone-0606',
    authDomain: 'instagram-clone-0606.firebaseapp.com',
    storageBucket: 'instagram-clone-0606.appspot.com',
  );
}
